### ISSUE TITLE
Log is not produced when test using Verify fails

### ISSUE THREAD

**Issue by MJB222398** [spekt/nunit.testlogger#106]
My project is an NUnit test one that uses Verify and NunitXml.TestLogger. I run it using the dotnet CLI, outputting results using the nunit logger.

If the test fails then inside the 'TestResults' directory I will see the .html and .trx files as expected but the nunit .xml file is not produced. If the test passes then I get the expected .xml file.

See this attached solution to reproduce the issue: 
[VerifyLoggerBug.zip](https://github.com/user-attachments/files/15970024/VerifyLoggerBug.zip)

To see the issue please run:

dotnet test --configuration Release --verbosity minimal --filter UnitTestFailing --logger:"html;LogFileName=TestResults.html" --logger:"trx;LogFileName=TestResults.trx;verbosity=detailed" --logger:"nunit;LogFileName=TestResults.xml;verbosity=detailed"

To see the report run correctly in the case that the test passes please run:

dotnet test --configuration Release --verbosity minimal --filter UnitTestPassing --logger:"html;LogFileName=TestResults.html" --logger:"trx;LogFileName=TestResults.trx;verbosity=detailed" --logger:"nunit;LogFileName=TestResults.xml;verbosity=detailed"

**Comment by codito** [comment]
Confirming the bug. Will track a fix as part of v4.x in https://github.com/spekt/testlogger.

```
TpTrace Error: 0 : 33122, 4, 2024/06/25, 20:22:32.382, 17343645580109, vstest.console.dll, MulticastDelegateUtilities.SafeInvoke: 3: Invoking callback 4/Spekt.TestLogger.Core.TestRunBuilder for .InternalTestLoggerEvents.SendTestRunComplete, failed after 12 ms with: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.Xml.Linq.XText..ctor(String value)
   at Microsoft.VisualStudio.TestPlatform.Extension.NUnit.Xml.TestLogger.NUnitXmlSerializer.CreateTestCaseElement(TestResultInfo result)
   at Microsoft.VisualStudio.TestPlatform.Extension.NUnit.Xml.TestLogger.NUnitXmlSerializer.CreateFixture(IGrouping`2 resultsByType)
   at Microsoft.VisualStudio.TestPlatform.Extension.NUnit.Xml.TestLogger.NUnitXmlSerializer.<>c.<CreateAssemblyElement>b__17_2(IGrouping`2 resultsByType)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at System.Linq.Enumerable.<Any>g__WithEnumerator|36_0[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.TestPlatform.Extension.NUnit.Xml.TestLogger.NUnitXmlSerializer.GroupTestSuites(IEnumerable`1 suites)
   at Microsoft.VisualStudio.TestPlatform.Extension.NUnit.Xml.TestLogger.NUnitXmlSerializer.CreateAssemblyElement(IGrouping`2 resultsByAssembly)
   at Microsoft.VisualStudio.TestPlatform.Extension.NUnit.Xml.TestLogger.NUnitXmlSerializer.<CreateTestRunElement>b__16_2(IGrouping`2 resultsByAssembly)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at Microsoft.VisualStudio.TestPlatform.Extension.NUnit.Xml.TestLogger.NUnitXmlSerializer.CreateTestRunElement(List`1 results, TestRunConfiguration runConfiguration)
   at Microsoft.VisualStudio.TestPlatform.Extension.NUnit.Xml.TestLogger.NUnitXmlSerializer.Serialize(LoggerConfiguration loggerConfiguration, TestRunConfiguration runConfiguration, List`1 results, List`1 messages)
   at Spekt.TestLogger.Core.TestRunCompleteWorkflow.Complete(ITestRun testRun, TestRunCompleteEventArgs completeEvent) in /home/runner/work/testlogger/testlogger/src/TestLogger/Core/TestRunCompleteWorkflow.cs:line 40
   at Spekt.TestLogger.Core.TestRunBuilder.<Subscribe>b__5_3(Object _, TestRunCompleteEventArgs eventArgs) in /home/runner/work/testlogger/testlogger/src/TestLogger/Core/TestRunBuilder.cs:line 55
   at InvokeStub_EventHandler`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Microsoft.VisualStudio.TestPlatform.Utilities.MulticastDelegateUtilities.SafeInvoke(Delegate delegates, Object sender, Object args, String traceDisplayName) in /build/dotnet-core/src/dotnet/src/vstest/artifacts/source-build/self/src/src/Microsoft.TestPlatform.CoreUtilities/Utilities/MulticastDelegateUtilities.cs:line 59.
```

**Comment by codito** [comment]
Root cause: Verify test failure is creating an attachment without description. This is leading to the nullref in above call stack.

**Comment by SimonCropp** [comment]
why doesnt the exception bubble?

or at least log?

**Comment by codito** [comment]
It bubbles but is swallowed by the test platform (extension failures are not shown in the cli). We will add error handling to catch and report such failures from the logger.

Logger logs are provided by the test platform via `dotnet test --diag:log.txt` (this is the source of the stacktrace in previous comment).

**Comment by SimonCropp** [comment]
@codito thanks for the clarification

**Comment by MJB222398** [comment]
@codito thanks for quick investigation. Do you have a rough release date for this fix ?

**Comment by codito** [comment]
@MJB222398 will try to release in a week or so.

Pre-release package `v4.0.226` with fix is available at https://www.myget.org/feed/spekt/package/nuget/NunitXml.TestLogger. Please test if this fixes the issue.

**Comment by MJB222398** [comment]
Hi @codito, Sorry to chase, is there an update on when this will be released?

**Comment by codito** [comment]
@MJB222398 sorry for the delay, here's the new release: https://www.nuget.org/packages/NunitXml.TestLogger/4.0.254

**Comment by MJB222398** [comment]
@codito Thanks!
