### ISSUE TITLE
Two properties created with the name 'Description' when using NUnit.ShowInternalProperties=true

### ISSUE THREAD

**Issue by sonudavidson** [spekt/nunit.testlogger#84]
In reference to the #79 & #69, As suggested, I added -- NUnit.ShowInternalProperties=true and indeed that did work. Although not completely as expected. In the result file, we now have 2 properties with the name Description in my result file. 

Attached a result file for your reference.

[TestResults.xml.txt](https://github.com/spekt/nunit.testlogger/files/6700189/TestResults.xml.txt)

**Comment by codito** [comment]
@sonudavidson thank you for reporting the issue. 

1. Could you please share the nunit xml generated in the `TestOutputXml` folder:

```sh
dotnet test --logger:nunit -- NUnit.TestOutputXml=<foldername relative to test binary directory>
```

2. Would it be possible to share the test method code? Just method name and attributes will be good.

**Comment by sonudavidson** [comment]
Hi @codito, The command 
`dotnet test --logger:nunit -- NUnit.TestOutputXml=<foldername>` throws an error in Linux machines. And almost all of our customers use only Linux machines. Although It works well in Windows machine. 

This is the error message 

`The active test run was aborted. Reason: Test host process crashed : Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'libActuator_testinterface.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibActuator_testinterface.so.so: cannot open shared object file: No such file or directory
   at Com.BLABLA.Actuator.UnitIntegrationTest.Definitions.Adaptors.ActuatorAdaptor.TestInterface_DestructActuator()
   at Com.BLABLA.Actuator.UnitIntegrationTest.Definitions.Adaptors.ActuatorAdaptor.Finalize() in /workspaces/actuator/internal/unitintegrationtest/Definitions/Adaptors/ActuatorAdaptor.cs:line 101

 

Test run in progress.Results File: /workspaces/actuator/internal/unitintegrationtest/GherkinSuites/TestResults/_3dfbf962a302_2021-06-22_19_52_41.trx
                                                                                                                                                                                                           
Test Run Aborted.`

Attached is how our typical test file would look like. 
[UnitTest1.cs.txt](https://github.com/spekt/nunit.testlogger/files/6727329/UnitTest1.cs.txt)

**Comment by codito** [comment]
Closing due to inactivity. Please reopen if this is still an issue.

I tried creating a test project with `dotnet new nunit`, used NunitXml.TestLogger `3.0.127`.

`dotnet test --logger:nunit -- NUnit.TestOutputXml=test2 NUnit.ShowInternalProperties=true` works as expected for below test code on linux box.

```csharp
namespace trial;

public class Tests
{
    [SetUp]
    public void Setup()
    {
    }

    [Test]
    [Description("Passing test description")]
    public void Test1()
    {
        Assert.Pass();
    }
}
```
